### PR TITLE
first pass

### PR DESCRIPTION
**Pull request by clarkbynum**

### CODE REVIEW

**Review by ronak-ingress — CHANGES_REQUESTED** [review]
@clarkbynum I have one thing to add here, as per the JIRA and current IDevice interface, we need to add following fields into the response,

```		    config?: (google.cloud.iot.v1.IDeviceConfig|null);

                    /** Device state */
                    state?: (google.cloud.iot.v1.IDeviceState|null);

                    /** Device logLevel */
                    logLevel?: (google.cloud.iot.v1.LogLevel|keyof typeof google.cloud.iot.v1.LogLevel|null);

                    /** Device metadata */
                    metadata?: ({ [k: string]: string }|null);

                    /** Device gatewayConfig */
                    gatewayConfig?: (google.cloud.iot.v1.IGatewayConfig|null);`

**Comment by ronak-ingress** [comment]
It is the second point in the JIRA, 
2) we specified in the fieldMask the metadata path but metadata not shown in the repsonse 

So we need to add this into our for loop, 

`for (const index in deviceListResponse.devices) {
              const device: protos.google.cloud.iot.v1.IDevice = {};
              device.id = deviceListResponse.devices[index].id;`

**Comment by clarkbynum** [comment]
@ronak-ingress can you clarify what you mean by including line numbers from the source code? I've changed things quite a bit since you last committed so I think the for loop you're referring to has been removed. Now the SDK just returns whatever is returned by the server. 

Note that there are a few changes needed on the server e.g., I noticed that Google always returns id and numId even if they're not specified in the fieldMask. 

I'll be writing tests for the listDevices method next week so we should have most of the cases ironed out

**Comment by ronak-ingress** [comment]
@clarkbynum Oh I see now, sorry was having an older develop branch, I have seen it's returning everything which comes from ClearBlade.

**Review by ronak-ingress — APPROVED** [review]

**Pull request merged**
